language: go
go:
- 1.5
before_deploy:
  - go get github.com/mitchellh/gox
  - gox
deploy:
  provider: releases
  api_key:
    secure: 04q187Wkcx1GkMjDqTvdt+5Aq2ZmohEtS9ztIzTxvdhwmmFrcRK/hh5zsmknQyScCg61f3VOcyizv27rRPFfyVBe9HX2UrofluMZ6e0i49hhgzQFt0v6SYOJG6m7rp38AQc06JE1gLzcOejFH6ris/TXNVIhmih84urClOPF4ELYkcvax4Os/lsh4nByOHtQowTkxMhO8f/Pc9V68NQuPjSJfQiyW3IM7LTguiQKJUdsI5/tA5OxziQS/mDLSVwCR3jecRoD9+zl1IAX2wxNsxHBjbZ2cbi9BDPJmOayTChFbLiCFhi3qwsCBAEZYrbkdYc5Yh1kBnT+CZTuPXBXPXrdla9SqwspiF3qF55FQOcw0bdBw5mLYqOmsKoHjH2QTSzGEwBS1cStuFjx42VxTvk5wvUOhl2LfW57LV1MZrdw1F6sFpPZwCuWUEb/s1UFgnU4MSJMAFxwVP0ycoR4bU+n74TyLXM1SDxk2Ou2i3nVrcZNCBRrJIHO4pa679KMOjsC9u4wvBNuV4VISV78/g2VEoFlp+vJGPECMnZc/0ZBAylS3m6ktvJRYKKGQRDqkr9Ir9CsTHqxCbHMHt9zQ/kW8D9JRnDVvJs4rbtiDDk78ezXo6+OXIq2dVQ0lRjT8+BsgDUtRqfnhBBKCHWMxudDGC+MKOabCa2QOqT2Wew=
  file:
    - "postmanerator_darwin_386"
    - "postmanerator_darwin_amd64"
    - "postmanerator_freebsd_386"
    - "postmanerator_freebsd_amd64"
    - "postmanerator_freebsd_arm"
    - "postmanerator_linux_386"
    - "postmanerator_linux_amd64"
    - "postmanerator_linux_arm"
    - "postmanerator_netbsd_386"
    - "postmanerator_netbsd_amd64"
    - "postmanerator_netbsd_arm"
    - "postmanerator_openbsd_386"
    - "postmanerator_openbsd_amd64"
    - "postmanerator_windows_386.exe"
    - "postmanerator_windows_amd64.exe"
  on:
    repo: aubm/postmanerator
    tags: true
